name: Train and Archive Reports

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'src/**'
      - 'requirements.txt'

jobs:
  train_archive:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: List data files
        run: |
          ls -la data || true

      - name: Run data mining (no SHAP)
        run: |
          python scripts/data_mining.py || true

      - name: Run CV training (CPU, fast)
        env:
          CUDA_VISIBLE_DEVICES: ''
        run: |
          python scripts/cv_train.py --folds 3 --n-jobs 2 --auto-drop-leakers || true

      - name: Archive reports
        run: |
          python scripts/archive_reports.py --out-dir submissions

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports-archive
          path: |
            submissions/reports_*.zip
            reports/**
          if-no-files-found: warn


